networks:
  ursa-auth-network:
    driver: bridge

services:
  ursa-auth:
    build: 
      dockerfile: Dockerfile.ursa-auth
      context: .
    container_name: ursa-auth-dev
    ports:
      - 4000:4000 # for Google OAuth redirect_uri restriction
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ursa-auth-network
  ursa-auth-test-next:
    build: 
      dockerfile: Dockerfile.next
      context: examples/next
    container_name: ursa-auth-test-next
    env_file:
      - examples/next/.env.development
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading
    volumes:
      - ./examples/next:/app
      - /app/node_modules
    tmpfs:
      - /app/.next
    networks:
      - ursa-auth-network
  ursa-auth-test-api:
    build:
      dockerfile: Dockerfile.api-server
      context: examples/api-server
    container_name: ursa-auth-test-api
    volumes:
      - ./examples/api-server:/app
    env_file:
      - examples/api-server/.env.development
    networks:
      - ursa-auth-network
  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /app/node_modules
    ports:
      - 80:80
    networks:
      ursa-auth-network:
        aliases:
          - auth.localhost
          - next.localhost
          - api.localhost

