services:
  ursa-auth:
    build: 
      dockerfile: Dockerfile.ursa-auth
      context: .
    container_name: ursa-auth
    ports:
      - 4000:4000
    env_file:
      - .env.development
    volumes:
      - .:/app
  ursa-auth-test-next:
    build: 
      dockerfile: Dockerfile.next
      context: examples/next
    container_name: ursa-auth-test-next
    env_file:
      - examples/next/.env.development
    ports:
      - 3000:3000
    volumes:
      - ./examples/next:/app
    tmpfs:
      - /app/.next
  ursa-auth-test-api:
    build:
      dockerfile: Dockerfile.api-server
      context: examples/api-server
    container_name: ursa-auth-test-api
    volumes:
      - ./examples/api-server:/app
    ports:
      - 5000:5000
    env_file:
      - examples/api-server/.env.development

networks:
  default:
    name: ursa-auth-network

