name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  app_links: ^6.4.0
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  http: ^1.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
